git.scmbrc.example, lib/git/shell_shortcuts.sh, test/lib/git/shell_shortcuts_test.sh
The `ls` aliases are nice, but can be pretty slow for big directories, depending on the hardware. And this is *SCM* Breeze, not *ls* Breeze
This makes them optional, with configuration variable `$shell_ls_aliases_enabled` (true by default).
=> Make ls aliases optional

lib/git/aliases.sh
Without this fix, all subcommands or options after the 2nd are truncated.
=> Fix argument expansion in __git_alias

lib/git/aliases.sh
This PR replaces `local varname=value` style declarations with `local varname; varname=value`. This solves #168 which caused troubles in zsh environments
=> Fixes #168 (zsh-problems)

lib/git/status_shortcuts.sh, test/lib/git/status_shortcuts_test.sh
Adds these two special characters to be quoted properly before eval. With unit test.
=> Fix quoting of semicolon and pipe

lib/git/aliases.sh
This patch fixes broken aliases which have arguments (e.g. gap)
=> Offset starts from 0 so the argument would be 3

lib/git/branch_shortcuts.sh
__git_alias expects three arguments. Passing two arguments to __git_alias for "gb" leads to undesirable behaviour on some platforms.
=> Fix setting alias for "_scmb_git_branch_shortcuts"

install.sh
Adds support for OS X's default bash configuration file,
`~/.bash_profile`, and more logging during install about
what to do if no shell configuration file was found.
=> Support for OS X .bash_profile + install logging

lib/git/fallback/status_shortcuts_shell.sh
Resolve symlinks to match `pwd`, so that `_gs_relative_path` does not loop forever.
=> Fix infinite loop in shell with babun (cygwin)

lib/git/repo_index.sh
If the shell has the noclobber option set, s --rebuild will fail to
update the .git_index file. Using the >| operator instead of the >
operator forces the .git_index file to be clobbered, which is the
desired behavior.
=> Use >| operator in _rebuild_git_index when overwriting .git_index file

lib/git/status_shortcuts.sh
Fixes this bug:
```
$ touch abc\&xyz
$ rm *xyz
[3] 16234
rm: abc: No such file or directory
[3]  + 16234 exit 1     /bin/rm abc
(eval):1: command not found: xyz
```
=> exec_scmb_expand_args: Escape ampersands.

git.scmbrc.example, lib/git/aliases.sh
Added `--init` to both, as I can't think of many cases when you explicitly _don't_ want `--init`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ndbroadbent/scm_breeze/159)
=> Add aliases for "git submodule update --init" and "git submodule update --init --recursive"

git.scmbrc.example, lib/git/aliases.sh
This creates an alias 'gapp' for 'git apply'
=> added 'git apply' alias

lib/git/repo_index.sh
Had to do this to pick up my golang code with `c --rebuild`. Think 5 is still pretty reasonable.
=> Bump git index depth to 5 for golang src structure

lib/git/status_shortcuts.sh
The current `git_clear_vars()` method appears to have iterated over all the existing set variable correctly, but seemingly never actually cleared them.  This fixes that behavior as best I can tell.
(That said, the extra variables weren't really hurting anybody before this fix, so maybe another option is the entire function should be deprecated to reduce the amount of operations a `gs` has to do in the interest of speed. Let me know what you prefer!)
=> BUGFIX: make `git_clear_vars()` actually clear variables

test/lib/git/shell_shortcuts_test.sh
On my system (Arch Linux), the commands {mv,rm,sed} live under
`/usr/bin`, not under `/bin`. So the tests were failing.
This commit hard-codes the initial paths to make the tests independent
on their real paths.
=> make tests independent of bin locations

scm_breeze.plugin.zsh
Modified install.sh to make it compatible with oh-my-zsh's plugin system.
I currently have this linked as a submodule in my custom plugins, but could just as easily be added to oh-my-zsh/plugins directly.
This way, there's no need to pollute your existing .zshrc file, as this will just load it along with everything else.
=> plugin-ified scm_breeze

lib/git/keybindings.sh
Consider adding keybindings to make multiline editing easier such as the following:
```sh
if [[ "$MC_SID" != "" || "$MC_CONTROL_PID" != "" ]]; then
bindkey "^J" accept-line
else
bindkey "^J" self-insert
fi
```
When this is done `\n` no longer submits the command but `^M` will work in both cases.
=> Use ^M instead of  for newlines

lib/git/status_shortcuts.rb
Hello there, I wanted to use the niced up git status but it was a little sluggish, so I took a look at it.
It appears that the original implementation queried git too much, which leads to bad performance - and to the `$gs_max_changes` variable.
I rewrote the script completely. Still works and looks the same though of course!
Looking at the benchmark results the effort was worth it:
```
git status               # => 0.233
status_shortcuts.rb-NEW  # => 0.270 | + 0.037
status_shortcuts.rb-OLD  # => 0.567 | + 0.334
git status               # => 0.104 
status_shortcuts.rb-NEW  # => 0.129 | + 0.025
status_shortcuts.rb-OLD  # => 0.246 | + 0.142
```
Interpreting these results a bit: The old implementation needs to query the git status twice, extrapolating these numbers (0.233 \* 2 = 0.466) tell …
=> Refactor of git status script

test/support/travisci_deps.sh
Travis CI env may have changed underneath us, so we need to update the apkg repositories before trying to install the `zsh` package.
=> Add apkg repository update before install

lib/git/fallback/status_shortcuts_shell.sh
If the parent directory does not exist, `dest` is empty which puts `_gs_relative_path` into an infinite loop and the `gs` command hangs.
resolves #241
=> Fix infinite loop when parent directory does not exist

README.md, install.sh, uninstall.sh
Fixes #300.
`.zshrc` can be found at `~/.zshrc` when `ZDOTDIR` is not set.
If ZDOTDIR is set, .zshrc is in `${ZDOTDIR}/.zshrc`.
Using parameter expansion, the hardcoded path can be replaced with
`${ZDOTDIR:-$HOME}/.zshrc`. That way, it'll use the value in
`ZDOTDIR` when set and the value in `HOME` when not.
This thus mirrors the usage of `ZDOTDIR` in zsh and makes the code
more flexible.
=> Use ZDOTDIR env variable for path to .zshrc

lib/git/shell_shortcuts.sh
Prior to this, if `$shell_ls_aliases_enabled="false"`, this code would still run, but unnecessarily.
=> Avoid running ll code if its not used

git.scmbrc.example, lib/git/aliases.sh
Add aliases for new commands: git switch and git restore. I first thought of `gr` or `grs` for git restore, but both were already used by other commands, thus `grt`. 
Resolves https://github.com/scmbreeze/scm_breeze/issues/295
=> Add aliases for git switch `gsw` / git restore `grt`

lib/git/status_shortcuts.rb
- Branch names containing dots (.) are now correctly parsed.
(although not sure why '\.' was in the regex in the first place.)
- Color/bold style is now correctly applied.
- Fixed a bug where no-change status is not detected.
before:
after:
=> `gs` fixes

README.md
Add a remark that ruby is more than just recommended (quick fix for https://github.com/scmbreeze/scm_breeze/issues/279)
I've run into this situation multiple times with fresh systems, so this PR contains a quick fix/reminder for the time until the ruby dependency is refactored out (if that's still a plan for the future).
=> README.md: add remark that some commands don't work w/o ruby

lib/git/shell_shortcuts.sh
I experienced this using VS Code in WSL, the `code` CLI is in the
Windows `PATH` that has a space in my user name.
Fixes #294.
=> Fix shell wrapping for exes with space in path.

lib/git/shell_shortcuts.sh
Alternative to #317 to fix #312.
I don't have a mac to test this on, if someone with a mac could test and confirm this is working as expected that would be excellent.
@patbl
```shell
$ if ! ls --version | grep GNU >/dev/null 2>&1; then echo "BSD"; else echo "GNU"; fi
GNU
Thu Jun 23 08:29:15 AM EDT 2022
0 ghthor@hivemind ~/.scm_breeze [test-bsd-ls]
```
=> Switch to output parse of `--version` to determine ls version

lib/git/status_shortcuts.rb
Fixes #322. The issue says it's deprecated in 3.2.0, however `.exists` has been deprecated for ages and was removed in 3.2.0. `scm_breeze` completely broke for me when upgrading ruby.
I was able to confirm this fixing the issue on my Mac 12.6, ruby 3.2.0.
=> Use File.exist over deprecated File.exists

lib/git/branch_shortcuts.sh
Return error code `0` if successfully call `git branch` instead of always returning `1`.
I have some commands that do things like `git branch -d blah && do-another-thing` and since I installed scm_breeze they broke. It appears scm_breeze was _always_ returning error code of 1 which broke things.
=> git:branch legacy return no error code when git branch succeeds.

README.md
The readme had the wrong suffix - setting GIT_REPO_DIR in `~/.git.scmrc` does not work, but setting it in `~/.git.scmbrc` does
=> fix rc file suffix in README

git.scmbrc.example
I've tested declaring the wrapped commands as an array in both zsh and bash and
both are working for me.
1. Closes #297
1. Closes #283
1. Closes #284
=> [example] switch to declaring wrapped commands as an array

scm_breeze.sh, scmbrc.example
`SCM_BREEZE_DISABLE_ASSETS_MANAGEMENT=true` will
disable the asset management portion of the shell integration.
I don't use it, I've never used it. I know I discussed with @vise890 years ago about how to remove it so we could have a lean core for the shell & git shortcuts part of this package.
It's still on by default, but adding the environment variable will disable it, so I'm going to merge this with the longterm intention of completely splitting these 2 systems apart.
=> feat: make the design/asset feature optional

scm_breeze.sh
Anyone who didn't opt out of the assets management feature (by setting SCM_BREEZE_DISABLE_ASSETS_MANAGEMENT) would be shown a nag message every time they started a shell, which adds unnecessary noise.
=> fix: Remove nag message for assets management

README.md
I have my editor set up to do automatic formatting and linting. I saved the README and noticed that it automatically updated the index as well, which I thought was pretty cool.
I also saw that the README still used the old TravisCI badge - I replaced this with one for GitHub actions.
Fixed all the broken image links - I migrated my blog from hugo to Ghost recently.
=> Updated README - Index, CI badge, Linting

README.md, git.scmbrc.example, lib/git/aliases.sh, lib/git/branch_shortcuts.sh, lib/git/compatibility.sh, lib/git/fallback/status_shortcuts_shell.sh, lib/git/grep_shortcuts.sh, lib/git/repo_index.sh, lib/git/shell_shortcuts.sh, lib/git/status_shortcuts.rb, lib/git/status_shortcuts.sh, lib/git/status_shortcuts_refactor.rb, lib/git/tools.sh, scm_breeze.sh, test/lib/git/compatibility_test.sh, test/lib/git/repo_index_test.sh, test/lib/git/shell_shortcuts_test.sh, test/lib/git/status_shortcuts_test.sh
When I originally wrote this I didn't know about: https://www.shellcheck.net/wiki/SC2154
> Note: This message only triggers for variables with lowercase characters in their name (foo and kFOO but not FOO) due to the standard convention of using lowercase variable names for unexported, local variables.
Whoops! So this change would fix a lot of shellcheck warnings in the scm_breeze source files, and also in my personal dotfiles (I have some custom functions that use scm_breeze.)
I would like to propose a backwards compatible fix so that we can use either `git_env_char` or `GIT_ENV_CHAR`  in `git.scmbrc`. This means that no-one has to change their existing config.
What do you think?
=> Use uppercase names for exported variables to avoid shellcheck warnings (SC2154)

test/lib/git/status_shortcuts_test.sh
This test was failing for me locally since my git config uses `main` as the default branch instead of `master`. I thought it would make sense to explicitly set `main` as the branch and update the expectations. (Setting it explicitly to `master` doesn't feel right!)
I would also be in favor of renaming our actual `master` branch to `main`. But I understand it's a controversial topic (especially these days), and other maintainers might have different opinions.
=> Fix test_git_status_shortcuts_merge_conflicts to use main branch explicitly - ignore config on local machines

.github/workflows/test.yml
[![facepalm](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/WjlTemxb6oA4PgZFmj08/90847050-76a2-4df0-ad36-97675936b7e2/facepalm.gif)](https://app.graphite.dev/settings/meme-library?org=voltusdev)
=> fix: gh-actions workflow broke after default branch rename

lib/git/aliases.sh, lib/git/branch_shortcuts.sh, lib/git/fallback/status_shortcuts_shell.sh, lib/git/keybindings.sh, lib/git/repo_index.sh, lib/git/shell_shortcuts.sh, lib/git/status_shortcuts.sh, lib/git/tools.sh, lib/scm_breeze.sh, test/lib/git/status_shortcuts_test.sh
This fixes conflicts where when direnv/nix develop activates it would unset this global `shell` variable.
=> fix: replace global `shell` variable with JIT shell detection

lib/git/shell_shortcuts.sh
When utilizing direnv and nix on darwin, you can enter directories and
have the ls flavor change from BSD to GNU. This change fixes those cases
by not caching which ls flavor we found at initialization time and
instead JIT'ing which flavor we have at each execution point.
=> feat: enable JIT detection of ls flavor

.github/workflows/test.yml
1. update nix install action version
Should fix the CI failures
=> fix: update gh action nix install

lib/scm_breeze.sh
This PR updates the `git pull` command in `update_scm_breeze` to use `main` instead of `master`.
=> Fix branch name to main in update_scm_breeze
